# Generated by Django 4.2.4 on 2023-09-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='persian_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
